export const GameAssets = {
  images: [
    { key: 'woodenCrate', url: 'https://play.rosebud.ai/assets/woodenCrate.png?HiYY' },
    { key: 'torch', url: 'https://play.rosebud.ai/assets/torch.png?9jBq' },
    { key: 'cobblestoneTile', url: 'https://play.rosebud.ai/assets/cobblestoneTile.png?XVTI' },
    { key: 'bottleOfRegret', url: 'https://play.rosebud.ai/assets/BottleOfRegretWeaponModel.png?71T8' },
    { key: 'boomerangFlask', url: 'https://play.rosebud.ai/assets/BoomerangFlaskModel.png?iAq4' },
    { key: 'weaponUpgrader', url: 'https://play.rosebud.ai/assets/WeaponUpgrader.png?TjmZ' },
    { key: 'UIPause', url: 'https://play.rosebud.ai/assets/UIPause.png?HDsQ' },
    { key: 'UIPlay', url: 'https://play.rosebud.ai/assets/UIPlay.png?ZHFB' },
    { key: 'JackpotJavelinModel', url: 'https://play.rosebud.ai/assets/JackpotJavelinModel.png?Ba4g' },
    { key: 'JackpotJavelinDiceIcon', url: 'https://play.rosebud.ai/assets/JackpotJavelinDiceIcon.png?Q5vc' },
    { key: 'JackpotJavelinBuzzShieldIcon', url: 'https://play.rosebud.ai/assets/JackpotJavelinBuzzShieldIcon.png?IRmj' },
    { key: 'JackpotJavelinIconCherry', url: 'https://play.rosebud.ai/assets/JackpotJavelinIconCherry.png?UMxE' },
    { key: 'JackpotJavelinIconClown', url: 'https://play.rosebud.ai/assets/JackpotJavelinIconClown.png?exat' },
    { key: 'JackpotJavelinIconFire', url: 'https://play.rosebud.ai/assets/JackpotJavelinIconFire.png?3le2' },
    { key: 'JackpotJavelinIconMoney', url: 'https://play.rosebud.ai/assets/JackpotJavelinIconMoney.png?gPUf' },
    { key: 'JackpotJavelinIconSkull', url: 'https://play.rosebud.ai/assets/JackpotJavelinIconSkull.png?MGZp' },
    { key: 'MeatHornModel', url: 'https://play.rosebud.ai/assets/MeatHornModel.png?VEOE' },
    { key: 'PanicIcon', url: 'https://play.rosebud.ai/assets/MeatHornIconPanic.png?31PP' },
    { key: 'DeafenedIcon', url: 'https://play.rosebud.ai/assets/MeatHornBuffIconDeafened.png?0hOY' },
    { key: 'VulnerableIcon', url: 'https://play.rosebud.ai/assets/MeatHornBuffIconDeafened.png?0hOY' },
    { key: 'ArmorShredIcon', url: 'https://play.rosebud.ai/assets/MeatHornIconArmorShred.png?vtAK' }
  ],
  spritesheets: [
    { key: 'BottleOfRegretGhostlyEx', url: 'https://play.rosebud.ai/assets/BottleOfRegretGhostlyEx.png?3OUE', frameConfig: { frameWidth: 48, frameHeight: 48 } },
    { key: 'Ahab', url: 'https://play.rosebud.ai/assets/AhabBase.png?cVYm', frameConfig: { frameWidth: 48, frameHeight: 48 } },
    { key: 'Dave', url: 'https://play.rosebud.ai/assets/DaveBase.png?mF5P', frameConfig: { frameWidth: 48, frameHeight: 48 } },
    { key: 'Sean', url: 'https://play.rosebud.ai/assets/SeanBase.png?cDW7', frameConfig: { frameWidth: 48, frameHeight: 48 } },
    { key: 'Rocco', url: 'https://play.rosebud.ai/assets/RoccoBase.png?xCI2', frameConfig: { frameWidth: 48, frameHeight: 48 } },
    { key: 'Drew', url: 'https://play.rosebud.ai/assets/DrewBase.png?wzh9', frameConfig: { frameWidth: 48, frameHeight: 48 } },
    { key: 'AgentTer', url: 'https://play.rosebud.ai/assets/AgentTerBase.png?3P7K', frameConfig: { frameWidth: 48, frameHeight: 48 } },
    { key: 'TheSwan', url: 'https://play.rosebud.ai/assets/TheSwanBase.png?2kRi', frameConfig: { frameWidth: 48, frameHeight: 48 } },
    { key: 'ClownKnife', url: 'https://play.rosebud.ai/assets/ClownKnife.png?JltF', frameConfig: { frameWidth: 48, frameHeight: 48 } },
    { key: 'BottleOfRegretGasCloud', url: 'https://play.rosebud.ai/assets/BottleOfRegretGasCloud.png?e8Y7', frameConfig: { frameWidth: 48, frameHeight: 48 }},
    { key: 'JackpotJavelinClownDecoy', url: 'https://play.rosebud.ai/assets/JackpotJavelinClownDecoy.png?kcSk', frameConfig: { frameWidth: 48, frameHeight: 48 } },
    { key: 'MeatHornConeSpriteSheet', url: 'https://play.rosebud.ai/assets/MeatHornConeSpriteSheet.png?4KvB', frameConfig: { frameWidth: 48, frameHeight: 48 } },
  ],
  audio: [
    { key: 'mainmenu', url: 'https://play.rosebud.ai/assets/mainmenu.mp3?JvcR' },
    { key: 'normalgameplay', url: 'https://play.rosebud.ai/assets/normalgameplay.mp3?BN8f' },
    { key: 'bottleSwing', url: 'https://play.rosebud.ai/assets/BottleOfRegretSwing.mp3?10pB' },
    { key: 'bottleHit', url: 'https://play.rosebud.ai/assets/BottleOfRegretHit.mp3?iS8Z' },
    { key: 'boomerangThrow', url: 'https://play.rosebud.ai/assets/BoomerangFlaskThrow.mp3?sQaC' },
    { key: 'boomerangCatchSuccess', url: 'https://play.rosebud.ai/assets/BoomerangFlaskCatch Success.mp3?augC' },
    { key: 'boomerangCatchFail', url: 'https://play.rosebud.ai/assets/BoomerangFlaskCatchFail.mp3?BDo8' },
    { key: 'boomerangRicochet', url: 'https://play.rosebud.ai/assets/BoomerangFlaskRicochet.mp3?GvVx' },
    { key: 'boomerangSpin', url: 'https://play.rosebud.ai/assets/BoomerangFlaskSpinFX.mp3?JBYh' },
    { key: 'BoomerangCrit', url: 'https://play.rosebud.ai/assets/BoomerangCrit.mp3?UxUf' },
    { key: 'BottleOfRegretCrit', url: 'https://play.rosebud.ai/assets/BottleOfRegretCrit.mp3?eIGs' },
    { key: 'DefaultHit', url: 'https://play.rosebud.ai/assets/DefaultHit.mp3?O2wu' },
    { key: 'DefaultDeath', url: 'https://play.rosebud.ai/assets/DefaultDeath.mp3?9q4U' },
    { key: 'DefaultIntro', url: 'https://play.rosebud.ai/assets/DefaultIntro.mp3?wntm' },
    { key: 'TheSwanIntro', url: 'https://play.rosebud.ai/assets/TheSwanIntro.m4a?CFD4' },
    { key: 'TheSwanHit', url: 'https://play.rosebud.ai/assets/TheSwanHit.m4a?lT41' },
    { key: 'TheSwanDeath', url: 'https://play.rosebud.ai/assets/TheSwanDeath.m4a?iupq' },
    { key: 'AhabHit', url: 'https://play.rosebud.ai/assets/AhabHit.m4a?GgdD' },
    { key: 'AhabDeath', url: 'https://play.rosebud.ai/assets/AhabDeath.m4a?m49e' },
    { key: 'JackpotJavelinStab', url: 'https://play.rosebud.ai/assets/JackpotJavelinStab.mp3?N3hl' },
    { key: 'JackpotJavelinSlotSpin', url: 'https://play.rosebud.ai/assets/JackpotJavelinSlotSpin.mp3?nT73' },
    { key: 'JackpotJavelinFailSpin', url: 'https://play.rosebud.ai/assets/JackpotJavelinFailSpin.mp3?GX1b' },
    { key: 'JackpotJavelinJackpotTrigger', url: 'https://play.rosebud.ai/assets/JackpotJavelinJackpotTrigger.mp3?tWgX' },
    { key: 'JackpotJavelinFireExplosion', url: 'https://play.rosebud.ai/assets/JackpotJavelinFireExplosion.mp3?IGYO' },
    { key: 'JackpotJavelinClownDecoySpawn', url: 'https://play.rosebud.ai/assets/JackpotJavelinClownDecoySpawn.mp3?ijxa' },
    { key: 'MeatHornAttack', url: 'https://play.rosebud.ai/assets/MeatHornAttack.mp3?wKTT' },
    { key: 'MeatHornCharge', url: 'https://play.rosebud.ai/assets/MeatHornCharge.mp3?Ht0x' },
    { key: 'MeatHornClownCrusher', url: 'https://play.rosebud.ai/assets/MeatHornClownCrusher.mp3?qujr' },
    { key: 'MeatHornOvercharge', url: 'https://play.rosebud.ai/assets/MeatHornOvercharge.mp3?OAOE' },
    { key: 'MeatHornPanicSFX', url: 'https://play.rosebud.ai/assets/MeatHornPanicSFX.mp3?5iMN' },
    { key: 'ClownKnifeDeath', url: 'https://play.rosebud.ai/assets/ClownKnifeDeath.m4a?cC3o' },
  ],
};